pipeline {
   agent any

   stages {
      stage('Git check out') {
         steps {
            
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '5eed4d0c-ac98-49aa-9f10-cbe3524a6297', url: 'https://github.com/arbiswas1990/samplemavenwar.git']]])
         }
      }
       stage('Build') {
         steps {
            echo 'I am in build stage'
         }
      }
      
       stage('Deploy') {
         steps {
            echo 'I am in deploy stage'
         }
      }
      
   }
}
